# Generated by Django 4.1.1 on 2022-10-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('test_date', models.DateField()),
                ('rbc_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hgb_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hct_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mcv_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mch_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mchc_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wbc_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plt_level', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
