# Generated by Django 4.1.1 on 2022-09-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testresults', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testresults',
            new_name='Testresult',
        ),
    ]
