# Generated by Django 4.1.1 on 2022-09-11 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testresults', '0002_rename_testresults_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
